from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, ContextTypes, filters
import random

# 🔐 Token
TOKEN = "7860141496:AAFO-2Y8RzsCwX2a1IPkd11pSxg0b3pgKwo"

# 😂 50+ ta kulgili roast hazillar
roasts = [
    "{} sinfda shunaqa yomon o‘qiydiki, doskaga chiqsa marker ham qochib ketadi!",
    "{} telefonni ko‘tarib 'Alo' deb aytguncha zaryadi tugaydi.",
    "{} Minecraftda zombi uni ko‘rib 'yo‘q, men bunaqa darajada pastga tushmayman' deydi.",
    "{} Google'dan savol so‘rasa, Google o‘chib qoladi.",
    "{} shunchalik qiziqki, multik ham undan zerikadi.",
    "{} bilan gaplashgan kompyuter o‘zini o‘chirdi: ‘Windows needs a break’.",
    "{} ni hazm qilish Google Translate uchun ham qiyin.",
    "{} ni ko‘rib Wi-Fi ham signal uzatishni xohlamaydi.",
    "{} ni eshitib Siri o‘zini o‘chirib qo‘ydi.",
    "{} gapirsa, hatto robotlar ham qochib ketadi.",
    "{} ni aqliga qarab AI ham chalkashib ketdi.",
    "{} dan keyin klaviatura ham o‘zini sindirib tashladi.",
    "{} ni ko‘rib captcha ham yig‘lab yubordi.",
    "{} ni hazm qilishdan ko‘ra BIOS yangilash osonroq.",
    "{} ni ko‘rib TikTok ham video yuklamaslikka qaror qildi.",
    "{} so‘zlasa, kompyuter o‘z-o‘zini format qilib yuboradi.",
    "{} ni yuzini ko‘rib kamera “lens error” dedi.",
    "{} ni gapidan keyin disk ham aylanishdan to‘xtadi.",
    "{} bilan suhbatdan keyin AI depresiyaga tushdi.",
    "{} da aqllilik bo‘lsa, Wi-Fi kabelsiz ishlaydi.",
    "{} ni hazm qilishdan ko‘ra reklamasiz YouTube topish oson.",
    "{} bilan gaplashishdan ko‘ra, Windows yangilanishi kutgan yaxshi.",
    "{} ga kulib bo‘lmaydi, chunki tizim uni jiddiy qabul qilmadi.",
    "{} ni eshitib antivirus ham o‘zini o‘chirib qo‘ydi.",
    "{} bilan gaplashgan telefon zaryadni o‘zi tugatadi.",
    "{} ni ko‘rib simob ham qochib ketdi.",
    "{} ni eshitgandan ko‘ra, reklama ko‘rgan yaxshi.",
    "{} dan keyin Google ham “I give up” dedi.",
    "{} da mantiq bo‘lsa, telefonni tosh bilan zaryadlash mumkin.",
    "{} ni hazm qilish uchun 1TB RAM kerak.",
    "{} ni so‘zidan keyin kalit so‘zlar ishlamaydi.",
    "{} ni fikri chatni lag qildiradi.",
    "{} da aql topish – Minecraft’da olmosni qopqoqdan topishga o‘xshaydi.",
    "{} gapirsa, translate ham “404 Not Found” qaytaradi.",
    "{} ni suhbati Face ID’ni chalkashtirib yuboradi.",
    "{} gapirganida hatto donishmandlar ham shokka tushadi.",
    "{} ni gapini eshitib, kaktus ham stressga tushdi.",
    "{} bilan 1 daqiqa – 1 soatlik qiynoqqa teng.",
    "{} ni hazm qilishdan ko‘ra, BIOS tilini tushunish oson.",
    "{} bilan suhbat — YouTube reklamasining hamma qismlarini ketma-ket ko‘rishdek.",
    "{} dan keyin progress bar ham to‘xtab qoldi.",
    "{} ni eshitib, calculator ham error berdi.",
    "{} ni gapiga Siri: “Bu javobdan voz kechaman.” dedi.",
    "{} dan keyin hatto lag ham lag qiladi.",
    "{} bilan gaplashgan Telegram bot o‘zini ban qiladi.",
    "{} haqida fikr yuritishdan ko‘ra, 1000 captcha yechgan oson.",
    "{} bilan suhbatdan keyin ChatGPT ham chiqib ketadi.",
    "{} ni fikrini tahlil qilish uchun quantum kompyuter kerak.",
    "{} ni yuzidan Face Unlock qochadi.",
    "{} ni so‘zida grammatik xatoliklar stressga tushadi.",
    "{} gapirganda internet o‘zi uzilib qoladi.",
    "{} dan iltimos qilish – notepad bilan GTA o‘ynashga urinish.",
    "{} ni ko‘rib, telefon selfi olishdan bosh tortadi.",
    "{} gapirganida hatto Minecraftdagi creeper ham o‘zini portlatmaydi.",
    "{} bilan gaplashish — Windows XP yangilanishi kutishga o‘xshaydi.",
    "{} ni eshitib, musiqa ilovasi kulgidan o‘chadi.",
    "{} ni so‘zidan keyin xotira kartasi o‘zini o‘chiradi.",
    "{} dan keyin quvvat bank ham zaryad bermaydi.",
    "{} bilan suhbat — loading ekranida abadiy qolish.",
    "{} ni eshitib, hatto TikTok trendi ham orqaga qaraydi.",
    "{} gapirganida klaviatura “Ctrl+Z” bosishni o‘zi xohlaydi.",
    "{} ni ovozidan Google Assistant o‘zini tutolmaydi.",
    "{} dan keyin signal minorasi teskari ishlaydi.",
    "{} ni gapida mantiq qidirish – Pixel 1 bilan Fortnite o‘ynashga urinish.",
    "{} bilan gaplashgan sun'iy intellekt rejalik dam olishga chiqadi.",
    "{} bilan suhbat –  dial-up internetdan foydalangandek hissiyot beradi.",
    "{} ni hazm qilish uchun 3D printerga hayot kerak.",
    "{} da shunchalik mantiq yo‘qki, calculator ham yig‘lab yuboradi.",
    "{} gapirsa, dasturchilar kodni qayta o‘ylab chiqishadi.",
    "{} ni ko‘rib telefon: “Tayyor emasman” dedi.",
    "{} da fikr yo‘qligi CPUni sovutishday sovuq.",
    "{} bilan suhbat – reklama ko‘rishga qaraganda qiyinroq.",
    "{} ni eshitgan Google: “Bunaqa so‘rov yo‘q” dedi.",
    "{} gapirganda hatto lag ham qochib ketadi.",
    "{} ni fikri — TikTokdagi 5-soniyali challengega yutqazgan.",
    "{} dan keyin robotlar ham “factory reset” qiladi.",
    "{} bilan suhbat – bootloop’da qolgan telefon kabi.",
    "{} ni gapidan keyin RAM o‘zini tozalab chiqadi.",
    "{} gapirsa, internet “404: Logic Not Found” chiqaradi.",
    "{} bilan gaplashganidan keyin signal kuchi 0gacha tushadi.",
    "{} ni hazm qilish — yozda sovuq kofe topishdek.",
    "{} gapirganda TikTok ham yutubga ko‘chib ketadi.",
    "{} da shunchalik mazmun yo‘qki, SSD ham joy ajratmaydi.",
    "{} ni yuzini tanib Face ID telefonni bloklab qo‘yadi.",
    "{} bilan gaplashish – 1GB update kutishdan og‘irroq.",
    "{} ni eshitgandan keyin progress bar ortga qarab yuradi.",
    "{} da mantiq – ping 999ms bo‘lsa ham ishlamaydi.",
    "{} ni gapidan keyin klaviatura tugmalari chiqib ketadi.",
    "{} ni ko‘rib Siri: “Xayr, men ketdim” dedi.",
    "{} dan keyin kompyuter BIOSga qaytib ketadi.",
    "{} bilan gaplashish – GTA’da suvda mashina minib yurgandek.",
    "{} ni eshitib, loading screen ham uchib ketdi.",
    "{} gapirganida signal “flight mode”ga o‘tadi.",
    "{} bilan gaplashish – xotirasiz telefon bilan video olishga o‘xshaydi.",
    "{} dan keyin kalkulyator xatolik beradi: ‘Divide by 0 logic’.",
    "{} ni gapidan keyin sensorli ekran ham bosilmaydi.",
    "{} da mantiq – 2% zaryad bilan 4 soat video ko‘rishdek.",
    "{} bilan suhbatdan keyin hatto reklama xush yoqadi.",
    "{} dan keyin telefon ekrani o‘chadi va yana yoqilmaydi.",
    "{} ni yuzini ko‘rib filterlar ham ishlamaydi.",
    "{} gapirganda mikrafon “muted” bo‘ladi o‘zidan-o‘zi.",
    "{} bilan gaplashgan bot “Offline Mode”ga o‘tadi.",
    "{} da mantiq bo‘lsa, toshda simkart bo‘ladi.",
    "{} ni fikri – screenshot qilsa telefon buziladi.",
    "{} gapirsa, yangilanish kutayotgan Windows ham jim qoladi.",
    "{} bilan gaplashish – 90-lardagi modem bilan 4K video ko‘rishga o‘xshaydi.",
    "{} ni eshitib, Apple ham Androidga o‘tadi.",
    "{} dan keyin hatto loading screen ham yonib qoladi.",
    "{} gapirganda Face Unlock tizimni qattiq qayta yuklaydi.",
    "{} ni yuzidan front kamera o‘zini yopadi.",
    "{} bilan gaplashish – soat 3:00 da budilnik signalini kutishga o‘xshaydi.",
    "{} bilan suhbatdan so‘ng operatsion tizim yangilanishdan bosh tortadi.",
    "{} ni eshitganda RAM “out of memory” chiqaradi.",
    "{} bilan gaplashish – “Unknown USB device”ga ulanib olgandek.",
    "{} dan keyin screenshotni ham telefon qabul qilmaydi.",
    "{} bilan suhbat – 56k modem bilan live stream qilishga o‘xshaydi.",
    "{} gapirganda, hatto kod editor ham ishlamay qoladi.",
    "{} ni fikrini o‘qigan AI – boshqa kasb izlaydi.",
    "{} bilan gaplashgan kompyuter o‘zini o‘chirdi: ‘Windows needs a break’.",
    "{} gapirganda, hatto ChatGPT ham 'bugun dam olaman' deydi.",
    "{} da aql topish – karavot ostidan Wi-Fi tutishga o‘xshaydi.",
    "{} Minecraft’da olmos topaman deb, lavada suzadi.",
    "{} ni eshitganda Siri mikrofonni yopib qo‘yadi.",
    "{} haqida film olishsa, janri: ‘Error 404: Logic not found’.",
    "{} ni aqlli deydigan odam, toshni PowerBank deb o‘ylaydi.",
    "{} ni fikridan keyin kalkulyator ham yig‘lab yuboradi.",
    "{} gapirganda, hatto robotlar 'format' so‘raydi.",
    "{} ni yuzini Face ID tanimaydi, telefon qo‘rqib o‘chadi.",
    "{} ni hazm qilishdan ko‘ra, Blue Screen of Death yaxshi.",
    "{} telefonni zaryadga qo‘yadi, lekin zaryad undan qochadi.",
    "{} Minecraftda zombilarni emas, zombilar uni qochadi.",
    "{} bilan suhbat – reklama ko‘rishdan battar azob.",
    "{} YouTube’da 'skip ad' tugmasini qidirmaydi, chunki hatto reklama ham undan charchaydi.",
    "{} darsda shunaqa jimki, hatto mikrofon uni sezmaydi.",
    "{} kuchli deb o‘ylaydi o‘zini, lekin changyutgichdan yengiladi.",
    "{} aqlli bo‘lsa, toshda TikTok ishlaydi.",
    "{} qachon fikr qilsa, loading screen ochiladi.",
    "{} ni ko‘rib hatto printer 'no paper' deb chiqadi.",
    "{} kulsa, kalit so‘zlar ishlashdan to‘xtaydi.",
    "{} ni fikrini tahlil qilish uchun NASA kompyuteri kerak.",
    "{} gapirganida dasturchilar kodni qayta yozishadi.",
    "{} shunaqa zerikarli, hatto statusi ham 'offline'.",
    "{} ni gapidan keyin RAM o‘zini tozalab chiqadi.",
    "{} internetdan aql qidiradi, lekin virus yuklaydi.",
    "{} bilan 1 daqiqa – 1 soatlik azobdek.",
    "{} o‘ylagan paytda serverlar 'maintenance'ga o‘tadi.",
    "{} ni eshitganda, kalkulyator 'syntax error' deydi.",
    "{} Minecraftda g‘orda yurgani yo‘q – to‘g‘ridan-to‘g‘ri pastga qulagan.",
    "{} haqida Google: 'Bunday ma’lumot mavjud emas' deb chiqardi.",
    "{} bilan gaplashgan telefon 'flight mode'ga o‘tadi.",
    "{} klaviaturaga qarasa, tugmalar qochadi.",
    "{} Face ID uni taniganida telefon o‘zini bloklaydi.",
    "{} ni gapidan keyin zaryad 100% dan 0% ga tushadi.",
    "{} aql bilan kuchli, lekin har doim noto‘g‘ri simga ulanadi.",
    "{} ni eshitib, sun’iy intellekt ruxsat olmasdan ketib qoladi.",
    "{} gapirganda signal minorasi pastga tushadi.",
    "{} bilan suhbat – 56k modemda 4K video ko‘rishga o‘xshaydi.",
    "{} da shunchalik aql yo‘qki, TikTok ham tan olmaydi.",
    "{} bilan kod yozish – notepad’da Fortnite o‘ynashga o‘xshaydi.",
    "{} ni ko‘rib CAPTCHA ham yig‘laydi.",
    "{} so‘zlasa, antivirus 'self-destruct' qiladi.",
    "{} ga kulish emas, sistemani qayta yuklash kerak.",
    "{} aqlli bo‘lsa, toshda Wi-Fi bo‘ladi.",
    "{} ni fikri – loading bar ortga yuradi.",
    "{} ni gapidan keyin mikrofon 'mute'ga o‘tadi.",
    "{} shunchalik zerikarli, hatto reklama ham qiziqarliroq.",
    "{} bilan gaplashgan AI boshqa ish qidira boshlaydi.",
    "{} gapirsa, Google Translate 'give up' qiladi.",
    "{} Minecraft’da creeper uni portlatmaydi – arzimaydi deb o‘ylaydi.",
    "{} bilan gaplashish – Not Responding oynasiga o‘xshaydi.",
    "{} kulsa, dinazavrlar qaytib keladi deb qo‘rqamiz.",
    "{} gapirsa, Bluetooth o‘zini o‘chiradi.",
    "{} haqida fikrlash – Wi-Fi signali yo‘q joyda Google ochishga o‘xshaydi.",
    "{} dan keyin hatto TikTok ham sekinlashadi.",
    "{} ni ko‘rib Face ID “yo‘q” deydi.",
    "{} bilan gaplashgan kompyuter “Sleep Mode”ga o‘tadi.",
    "{} sinfda shunaqa jimki, hatto mikrofon signal topolmaydi.",
    "{} Minecraftda suvda cho‘kadi, lekin oyog‘i yerda turadi.",
    "{} ni fikri – lag bo‘lgan aql versiyasi.",
    "{} ni aqliga antivirus ham yordam bera olmaydi.",
    "{} sinfda shunaqa yomon o‘qiydiki, doskaga marker chiqmay qo‘yadi.",
    "{} ni hazm qilish uchun AI ham qayta treningga muhtoj.",
    "{} ni eshitganda calculator ham “Error” deydi.",
    "{} da mantiq bo‘lsa, toshda TikTok bo‘ladi.",
    "{} bilan gaplashish – GTA’da velosiped bilan samolyot quvishga o‘xshaydi.",
    "{} gapirganda, telefon zaryadi o‘zi ketadi.",
    "{} hatto selfie olishdan oldin kamera o‘zini yopadi.",
    "{} ni ko‘rib YouTube reklamalari o‘zini yo‘qotadi.",
    "{} ni aqli 2G’dan ham sekin ishlaydi.",
    "{} o‘ylasa, progress bar orqaga yuradi.",
    "{} raqam aytsa, kalkulyator shokka tushadi.",
    "{} dan so‘ng mikroto‘lqinli pech ham sovib qoladi.",
    "{} ni Google qidiruvdan ban qilgan.",
    "{} ni eshitganda robotlar stressga tushadi.",
    "{} ni gapidan keyin hatto siri “restart” qiladi.",
    "{} shunaqa darajada chalkashki, QR kod ham uni o‘qiy olmaydi.",
    "{} da aql topish – olmaxon bilan shaxmat o‘ynashga o‘xshaydi.",
    "{} haqida AI so‘rasang, “not enough data” deydi.",
    "{} bilan suhbat — reklamasiz YouTube topishdek.",
    "{} bilan gaplashganidan keyin hatto lampochka ham so‘nadi.",
    "{} Minecraft'da creeper ham portlashdan bosh tortadi.",
    "{} signal darajasi shunaqa pastki, hattoki SIM karta qochib ketgan.",
    "{} ni gapini eshitganda, kodlar o‘zini tuzatmay qo‘yadi.",
    "{} ni hazm qilish – SSD’da DOS o‘rnatishga teng.",
    "{} gapirsa, notepad ham tizimdan chiqadi.",
    "{} bilan gaplashish – dial-up internetda video qo‘ng‘iroq qilishga o‘xshaydi.",
    "{} da mantiq izlash – kar boshqotirma yechishga o‘xshaydi.",
    "{} ni eshitganda mikrofon o‘zini “mute” qiladi.",
    "{} ni gapidan so‘ng sensorli ekran bosishga javob bermaydi.",
    "{} ni yuzini ko‘rib kamera: 'Lens Error'.",
    "{} gapirganda, xotira kartasi o‘zini format qiladi.",
    "{} bilan 1 daqiqa – AI uchun 1 oy stressga teng.",
    "{} da fikr yo‘qligi CPU’ni ham sovuq qiladi.",
    "{} ni ko‘rib, telefon selfi rejimini o‘chiradi.",
    "{} so‘zlasa, translate ham o‘zini bloklaydi.",
    "{} haqida gap ketsa, progress bar muzlab qoladi.",
    "{} ni aqli – PlayStation’da kalkulyator ishga tushirgandek.",
    "{} Minecraft’da lavani muzga aylantirib qo‘yadi – ahmoqlik bilan.",
    "{} ni gapidan keyin sensorli ekran ham o‘zini o‘chiradi.",
    "{} haqida aytsang, loading screen ortga yuradi.",
    "{} bilan suhbatdan keyin hatto ChatGPT ham dam oladi.",
    "{} yugursa, soya ham kulib qarab turadi.",
    "{} suzishga tushsa, baliqlar chiqib ketadi.",
    "{} telefonni qo‘lsa, tugmalar o‘zini o‘chiradi.",
    "{} yugurayotganida hatto tosh ham uni quvib o‘tadi.",
    "{}ni kulgisini eshitib, televizor ovozini o‘chiradi.",
    "{} Minecraftda uyni qurdi — Enderman ham kuldi.",
    "{} shunaqa sekin yuradiki, burgut uxlab qoladi.",
    "{} raqsga tushsa, musiqa to‘xtab qoladi.",
    "{} tishlarini yuvsa, cho‘tka yig‘laydi.",
    "{} keldimi — hatto robotlar xatolik beradi.",
    "{} shunaqa jimki, soat ham ishlashni to‘xtatadi.",
    "{} to‘p tepdi — to‘p o‘zini portlatdi.",
    "{} kulsa, quyosh ham ko‘zini yumadi.",
    "{} shunaqa baland gapiradiki, mikrofon o‘zini o‘chiradi.",
    "{} velosiped haydasa, g‘ildiraklar qochadi.",
    "{} TikTok ochdi — telefon kulib yubordi.",
    "{}ni eslab ko‘rsam, hatto Google ham topolmaydi.",
    "{} selfi qilsa, kamera qorong‘i tushadi.",
    "{} qizg‘anchiq shunaqaki, soyasini ham bermaydi.",
    "{} Minecraftga kirsa, zombilar qochib ketadi.",
    "{} raqamlarni aytsa, kalkulyator ham chalkashadi.",
    "{} ni qidirib topish oson, faqat kulgi yo‘q.",
    "{} rulda o‘tirsa, mashina ‘yo‘q’ deydi.",
    "{} oynaga qarasa, oynaning ichi qorong‘i bo‘lib qoladi.",
    "{} shunaqa kuchli hazil aytadiki, hatto kulgich ham jimgina qoladi.",
    "{} baliq tutsa, baliq suvdan chiqmaydi.",
    "{} zaryad qo‘ysa, telefon: ‘Kechirasiz, yo‘q’, deydi.",
    "{} gapirsa, Google Translate ham voz kechadi.",
    "{} donut yeydi — donut: ‘Men bundayga loyiq emasman’, deydi.",
    "{} yugursa, eshik yopilib qoladi.",
    "{} Minecraftga kirganda, Creeper o‘zini portlatmaydi — chiqib ketadi.",
    "{}ni ko‘rgan mushuk yig‘lab yuboradi.",
    "{} Minecraftda to‘pni urdi — server blokladi.",
    "{} hidi keldi — parfum yashirinib oldi.",
    "{}ni eshitganda, quloqchalar o‘zini sindiradi.",
    "{} tizza bilan yugursa, tizzasi ta’tilga chiqadi.",
    "{} shunchalik kulgili gapiradiki, kulgi ham charchab qoladi.",
    "{} TikTok ochsa, telfon o‘zini yangilab tashlaydi.",
    "{} yugursa, chang orqaga ketadi.",
    "{}ni oyog‘i yursa, yo‘l charchaydi.",
    "{} selfi qilishga urinsa, kamera: ‘Keyinroq iltimos’, deydi.",
    "{}ni telefon ko‘rsa, quvvat o‘zini yo‘qotadi.",
    "{} shunaqa sekin ishlaydiki, kapalak yetib oladi.",
    "{} Minecraftda teshik qaziydi — teshik: ‘Stop!’ deydi.",
    "{} gap boshlasa, havo o‘zini yo‘qotadi.",
    "{} ping-pong o‘ynasa, to‘p: ‘Qo‘rqdim’, deydi.",
    "{} bir marta kuchaygan edi — lampochka portladi.",
    "{} dars qilsa, ruchka: ‘Meni ishlatma’, deydi.",
    "{} yugurganda soya: ‘Men bilan yugurma’, deydi.",
    "{} gulga qarasa, gul so‘lib qoladi.",
    "{} kulsa, lolipop ham eriydi.",
    "{} shunchaki yuradi — asfalt stressga tushadi.",
    "{} shunaqa sekin gapiradiki, subwoofer ham uxlab qoladi.",
    "{} ni hazillaridan keyin hatto televizor signal yo‘qotdi.",
    "{} onlayn darsga kirganda kamera o‘zini o‘chirib qo‘ydi.",
    "{} kulganda boshqa odamlar yig‘lay boshlaydi.",
    "{} ni ovozi shunaqa pastki, hatto Google Assistant 'He?' deb so‘raydi.",
    "{} mikrofonni yoqsa, hamma quloqchinini yechadi.",
    "{} matematika darsida kalkulyatorni yig‘latdi.",
    "{} multfilm ko‘rsa, qahramonlar ekrandan qochib ketadi.",
    "{} testga kirganda savollar javob so‘radi.",
    "{} bilan shaxmat o‘ynasa, piyoda o‘zini tashlaydi.",
    "{} 'yozgi dam olish' deganda daftar xursand bo‘ladi.",
    "{} selfi olganda kamera teskari qaraydi.",
    "{} TikTok ochsa, app uni bloklaydi.",
    "{}ni quvgan soya ham charchab qoladi.",
    "{}ga SMS yozsam, telefonim uzr so‘radi.",
    "{} shunaqa gapiradiki, Google Translate jon beradi.",
    "{}ni ko‘rgan Minecraft zombi qochib ketadi.",
    "{}ga maktabdan uyga vazifa emas, uzr xati berishdi.",
    "{} o‘qituvchini yig‘latgan yagona daftar.",
    "{} tush ko‘rsa, hatto uyqudan ham qochadi.",
    "{} raqsga tushsa, musiqa o‘zini o‘chiradi.",
    "{}ni ovoziga hatto Siri 'shovqinli muhit' deb baho berdi.",
    "{} darsda o‘tirganda parta 'yana u keldi' deb xirillaydi.",
    "{} boshidan smartfon o‘tganda, u tugma telefon bo‘lib qoladi.",
    "{} onlayn testda savollar uni report qildi.",
    "{} yugursa, vaqt ham kutib turadi.",
    "{}ni topishmoqqa qo‘ysang, hech kim javob topolmaydi.",
    "{} rasm chizsa, qog‘oz o‘zini yirtadi.",
    "{} smart doskaga yaqinlassa, ekran o‘zini o‘chiradi.",
    "{} so‘z boshlasa, mikrofon 'Error 404' beradi.",
    "{} TikTok trenlarni boshlaydi — lekin hech kim qo‘shilmaydi.",
    "{}ni qo‘shiq aytgani bilan mikrofon yig‘laydi.",
    "{} telefon zaryad olmasdan oldin undan ruxsat so‘raydi.",
    "{}ni uyga chaqirishsa, devorlar ham chiqib ketadi.",
    "{} izoh yozsa, klaviatura yig‘laydi.",
    "{}ni videoga olishsa, kamera qora ekranga o‘tadi.",
    "{} YouTube izlashga urinsa, Google shokka tushadi.",
    "{} mem yaratganda, internet o‘zini o‘chiradi.",
    "{}ni kulgisidan keyin tomoshabinlar tomosha tugagandek chiqib ketadi.",
    "{} dan battar versiyasi faqat qog‘ozda bor — va u yo‘qolgan.",
    "{}dan hazil kutgan odam, oxiri uzr so‘raydi.",
    "{}ni robotlar tanimaydi — chunki ular uni odam deb qabul qilmaydi.",
    "{} uchun hatto AI ham 'Pass' deydi.",
    "{} kompyuterga kirganda, Windows o‘rnatishni rad etadi.",
    "{}ni ovozli xabaridan keyin Telegram ovozni to‘xtatdi.",
    "{} fizika qonunlarini buzmaydi — ular undan qochadi.",
    "{}ni so‘rash uchun hech kimga jur’at yetmaydi — hattoki savollar ham.",
    "{} bor joyda WiFi ham signal yo‘qotadi.",
    "{}ni topish uchun harita kerak emas — radar yetmaydi.",
    "{} jamoaga kelsa, hatto jamoa tarqab ketadi.",
    "{} televizorda ko‘rinsa, hatto pult ham ishlamaydi.",
]

# /start komandasi
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Salom! Kimni roast qilamiz? Ismini yozing.")

# Ism kirganda ishga tushadigan funksiya
async def handle_name(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.message.text:
        name = update.message.text.strip()
        roast = random.choice(roasts).format(name)
        
        # Bu yerda terminalga chiqariladi:
        print(f"📢 {update.effective_user.first_name} foydalanuvchi '{name}' ni roast qilyapti.")
        
        await update.message.reply_text(roast)
        await update.message.reply_text("Yana kimni roast qilamiz? Ismini yozing.")

# Botni ishga tushurish
if __name__ == '__main__':
    app = ApplicationBuilder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_name))
    print("🤖 Roast bot 200 ta super hazillar bilan ishga tushdi!")
    app.run_polling()
